workflows:
  - name: Default Workflow
    environment: 
      vars:
        - key: MY_VAR
          value: foobar
      xcode: 9.4.1
      flutter: stable
    cache:
      enabled: true
      cache_paths: 
        - '$FCI_BUILD_DIR/build'
    scripts:
      - cd examples/hello_world/
      - flutter packages pub get
      - flutter packages pub global activate webdev
      - flutter packages pub global run webdev build
    build_on_pr_update: True
    automatic_builds: True
    branch_patterns:
      - pattern: '*'
        include: true
